services:
  api:
    build: .
    container_name: learnify_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0
    container_name: learnify_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  
# __________________________ BACK ENTIGO __________________________

# services:
#   api-1:
#     build: .
#     container_name: Learnify_app
#     ports:
#       - "3000:3000"
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/LearniFy-TCC4-RnMobile-FullStack
#       - PORT=3000
#       - JWT_SECRET=seuSegredoAqui
#     # volumes:
#     #   - .:/usr/src/app
#     #   - /usr/src/app/node_modules
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo:latest
#     container_name: learnify_mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
# volumes:
#   mongo-data:
