version: "3.9"
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: ["mongo_data:/data/db"]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # S3 endpoint
      - "9001:9001" # console
    volumes:
      - "minio_data:/data"

  api:
    build: .
    env_file: .env
    ports: ["3000:3000"]
    depends_on: [mongo, minio]

volumes:
  mongo_data:
  minio_data:


# __________________________ BACK ENTIGO __________________________

# services:
#   api-1:
#     build: .
#     container_name: Learnify_app
#     ports:
#       - "3000:3000"
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/LearniFy-TCC4-RnMobile-FullStack
#       - PORT=3000
#       - JWT_SECRET=seuSegredoAqui
#     # volumes:
#     #   - .:/usr/src/app
#     #   - /usr/src/app/node_modules
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo:latest
#     container_name: learnify_mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
# volumes:
#   mongo-data:
