name: CI/CD - LearniFy (Build & Test)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    name: 游빍 Testes e Build
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --quiet --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: 游닌 Checkout do C칩digo
        uses: actions/checkout@v4

      - name: 游릭 Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: Back-End/package-lock.json

      - name: 游닍 Instalar Depend칡ncias
        working-directory: ./Back-End
        run: npm ci

      - name: 游빍 Rodar Testes (Jest)
        working-directory: ./Back-End
        run: npm test -- --coverage
        env:
          # Vari치veis exclusivas para o ambiente de CI
          NODE_ENV: test
          JWT_SECRET: "segredo_de_teste_ci_github"
          MONGO_URI: "mongodb://localhost:27017/LearniFy_Test"
          S3_BUCKET: "teste-bucket" # Mock para passar no CI
